Standardise function name/error string

diff --git a/note b/note
--- a/note
+++ b/note
@@ -126,10 +126,10 @@ note_show_version () {
 EOF
 }
 
-verify_date () {
+note_verify_date () {
   local date="$1"
   if ! [[ $date =~ ^[0-9]{4}(-[0-9]{2}){0,2}$ ]]; then
-    echo "Invalid date format (must be YYYY(-MM(-DD))): $date" >&2
+    echo "Invalid date format (must be YYYY[-MM[-DD]]): $date" >&2
     exit 1
   fi
 }
