Implement -d flag

diff --git a/todo b/todo
--- a/todo
+++ b/todo
@@ -34,6 +34,17 @@ function todo_write() {
     printf "$(todo_stamp)\t--\t[ ] $@\n" >> $TODO_FILE
 }
 
+function todo_do() {
+    local mark="$1"
+    [[ -z "$mark" ]] && printf "No item number given\n" && exit 1
+
+    local line=$(sed -n "$mark p" <<< "$(todo_undone)")
+    [[ -z "$line" ]] && printf "Invalid item number: $mark\n" && exit 1
+
+    local num=$(awk -F"\t" -v line="$line" '$0 == line {print NR}' "$TODO_FILE")
+    sed -i "${num}s/--\t\[ \]/$(todo_stamp)\t\[X\]/" $TODO_FILE
+}
+
 function todo_main() {
     if [[ $# -eq 0 ]]; then
         todo_print "$(todo_undone)"
@@ -54,6 +65,8 @@ function todo_main() {
         todo_print "$(todo_done)" "$num"
     elif [[ "$1" =~ ^-A[0-9]*$ ]]; then
         cat <(todo_print "$(todo_undone)" "$num") <(todo_print "$(todo_done)" "$num")
+    elif [[ "$1" =~ ^-d[0-9]*$ ]]; then
+        todo_do "$num"
     else
         todo_write "$@"
     fi
